# Generated by Django 5.1.4 on 2025-03-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_backend_checker', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('text', 'Text'), ('code', 'Code')], max_length=10)),
                ('content', models.TextField(unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
